apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: argo-demo
  labels:
    app.kubernetes.io/name: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
